version: "3.9"

services:
  app:
image: ghcr.io/gabriellyzup/container:latest   
 build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"  
    command: ["python", "main.py"]  
    environment:
      # Adicione variáveis de ambiente
    volumes:
      - .:/app  # Monta o diretório atual no contêiner

volumes: